#!/bin/bash

# Create Release Package
# Generates a clean tarball for distribution, excluding development files
# Usage: ./create-release.sh <version> [--no-publish]

set -e

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

# Parse arguments
VERSION=${1:-"latest"}
PUBLISH=true

if [[ "$2" == "--no-publish" ]] || [[ "$2" == "--local" ]]; then
    PUBLISH=false
fi

OUTPUT_DIR="./releases"
PACKAGE_NAME="php-harbor-${VERSION}"
TAG_NAME="v${VERSION}"

echo -e "${BLUE}━━━ PHPHarbor - Release Builder ━━━${NC}"
echo ""
echo "📦 Version: $VERSION"
echo "🏷️  Tag: $TAG_NAME"
echo "📤 Publish: $([ "$PUBLISH" = true ] && echo "Yes" || echo "No (local only)")"
echo ""

# Create output directory
mkdir -p "$OUTPUT_DIR"

# Files and directories to EXCLUDE (not needed by end users)
EXCLUDE_ITEMS=(
    ".git"
    ".github"
    "archive"
    "legacy"
    "docs/publishing.md"
    "create-release.sh"
    "releases"
    ".DS_Store"
    "*.bak"
    "projects/*"
    "!projects/README.md"
)

echo -e "${BLUE}Files excluded from release:${NC}"
for item in "${EXCLUDE_ITEMS[@]}"; do
    echo "  ❌ $item"
done
echo ""

# Generate build info
echo -e "${BLUE}Generating build info...${NC}"

GIT_HASH=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
GIT_COMMIT=$(git rev-parse HEAD 2>/dev/null || echo "unknown")
BUILD_DATE=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
BUILD_TIMESTAMP=$(date +%s)

# Create .build-info file
cat > .build-info << EOF
# PHPHarbor Build Information
# This file is generated automatically during release creation

VERSION="$VERSION"
GIT_HASH="$GIT_HASH"
GIT_COMMIT="$GIT_COMMIT"
BUILD_DATE="$BUILD_DATE"
BUILD_TIMESTAMP="$BUILD_TIMESTAMP"
REPOSITORY="https://github.com/v-merli/php-harbor"
EOF

echo -e "${GREEN}✓${NC} Build info generated"
echo "  Hash: $GIT_HASH"
echo "  Commit: $GIT_COMMIT"
echo "  Date: $BUILD_DATE"
echo ""

# Create tarball
echo -e "${BLUE}Creating tarball...${NC}"

tar -czf "$OUTPUT_DIR/${PACKAGE_NAME}.tar.gz" \
    --exclude='.git' \
    --exclude='.github' \
    --exclude='archive' \
    --exclude='legacy' \
    --exclude='docs/publishing.md' \
    --exclude='create-release.sh' \
    --exclude='releases' \
    --exclude='.DS_Store' \
    --exclude='*.bak' \
    --exclude='projects/*' \
    --exclude='.gitignore' \
    .

# Tarball information
SIZE=$(du -h "$OUTPUT_DIR/${PACKAGE_NAME}.tar.gz" | cut -f1)

echo ""
echo -e "${GREEN}✅ Release created successfully!${NC}"
echo ""
echo "📦 File: $OUTPUT_DIR/${PACKAGE_NAME}.tar.gz"
echo "📊 Size: $SIZE"
echo ""

# Tarball contents
echo -e "${BLUE}Tarball contents (main):${NC}"
tar -tzf "$OUTPUT_DIR/${PACKAGE_NAME}.tar.gz" | head -30
echo ""

# Checksum
echo -e "${BLUE}SHA256 Checksum:${NC}"
CHECKSUM=$(shasum -a 256 "$OUTPUT_DIR/${PACKAGE_NAME}.tar.gz")
CHECKSUM_HASH=$(echo "$CHECKSUM" | cut -d' ' -f1)
echo "$CHECKSUM"
echo ""

# Update RELEASE_NOTES.md with actual checksum
if [ -f "RELEASE_NOTES.md" ]; then
    echo -e "${BLUE}Updating RELEASE_NOTES.md with checksum...${NC}"
    if grep -q "\[will be generated" RELEASE_NOTES.md; then
        sed -i.bak "s/\[will be generated by create-release.sh\]/$CHECKSUM_HASH/" RELEASE_NOTES.md
        rm -f RELEASE_NOTES.md.bak
        echo -e "${GREEN}✓${NC} RELEASE_NOTES.md updated"
        
        # Commit the change if publishing
        if [ "$PUBLISH" = true ]; then
            git add RELEASE_NOTES.md
            git commit -m "Update RELEASE_NOTES.md checksum for v$VERSION" 2>/dev/null || true
            git push 2>/dev/null || true
            echo -e "${GREEN}✓${NC} Changes committed and pushed"
        fi
    else
        echo -e "${YELLOW}⚠${NC} No placeholder found in RELEASE_NOTES.md"
    fi
    echo ""
fi

# Publish to GitHub if requested
if [ "$PUBLISH" = true ]; then
    echo -e "${BLUE}━━━ Publishing to GitHub ━━━${NC}"
    echo ""
    
    # Check if gh CLI is installed
    if ! command -v gh &> /dev/null; then
        echo -e "${RED}✗ GitHub CLI (gh) is not installed${NC}"
        echo ""
        echo "Install GitHub CLI:"
        echo ""
        
        # Detect OS and show appropriate installation command
        if [[ "$OSTYPE" == "darwin"* ]]; then
            echo "  macOS:"
            echo "    brew install gh"
        elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
            echo "  Linux (Debian/Ubuntu):"
            echo "    sudo apt install gh"
            echo ""
            echo "  Linux (Fedora/RHEL):"
            echo "    sudo dnf install gh"
            echo ""
            echo "  Linux (Arch):"
            echo "    sudo pacman -S github-cli"
        elif [[ "$OSTYPE" == "msys" ]] || [[ "$OSTYPE" == "cygwin" ]] || grep -qi microsoft /proc/version 2>/dev/null; then
            echo "  Windows/WSL2:"
            echo "    Follow Linux instructions above"
        fi
        
        echo ""
        echo "  Or visit: https://cli.github.com/manual/installation"
        echo ""
        echo "Or run without publishing:"
        echo "  ./create-release.sh $VERSION --no-publish"
        echo ""
        exit 1
    fi
    
    # Check if authenticated
    if ! gh auth status &> /dev/null; then
        echo -e "${RED}✗ Not authenticated with GitHub${NC}"
        echo ""
        echo "Authenticate with:"
        echo "  gh auth login"
        echo ""
        exit 1
    fi
    
    # Check if tag already exists
    if git rev-parse "$TAG_NAME" &> /dev/null; then
        echo -e "${YELLOW}⚠ Tag $TAG_NAME already exists${NC}"
        read -p "Do you want to delete and recreate it? (y/N): " -n 1 -r
        echo
        if [[ $REPLY =~ ^[Yy]$ ]]; then
            git tag -d "$TAG_NAME"
            git push origin ":$TAG_NAME" 2>/dev/null || true
            echo -e "${GREEN}✓${NC} Old tag deleted"
        else
            echo -e "${RED}✗ Aborted${NC}"
            exit 1
        fi
    fi
    
    # Create git tag
    echo -e "${BLUE}Creating git tag...${NC}"
    git tag -a "$TAG_NAME" -m "Release $VERSION"
    echo -e "${GREEN}✓${NC} Tag created: $TAG_NAME"
    
    # Push tag to origin
    echo -e "${BLUE}Pushing tag to GitHub...${NC}"
    git push origin "$TAG_NAME"
    echo -e "${GREEN}✓${NC} Tag pushed to origin"
    echo ""
    
    # Read release notes if they exist
    RELEASE_NOTES=""
    if [ -f "RELEASE_NOTES.md" ]; then
        RELEASE_NOTES=$(cat RELEASE_NOTES.md)
    fi
    
    # Create GitHub release
    echo -e "${BLUE}Creating GitHub release...${NC}"
    
    if [ -n "$RELEASE_NOTES" ]; then
        gh release create "$TAG_NAME" \
            "$OUTPUT_DIR/${PACKAGE_NAME}.tar.gz" \
            --title "PHPHarbor $VERSION" \
            --notes "$RELEASE_NOTES"
    else
        gh release create "$TAG_NAME" \
            "$OUTPUT_DIR/${PACKAGE_NAME}.tar.gz" \
            --title "PHPHarbor $VERSION" \
            --notes "Release $VERSION"
    fi
    
    echo -e "${GREEN}✓${NC} Release published on GitHub"
    echo ""
    
    # Get release URL
    RELEASE_URL=$(gh release view "$TAG_NAME" --json url -q .url)
    
    echo -e "${GREEN}✅ Successfully published!${NC}"
    echo ""
    echo "🌐 Release URL: $RELEASE_URL"
    echo "📦 Asset: ${PACKAGE_NAME}.tar.gz"
    echo ""
    
    # Update install.sh URL
    echo -e "${YELLOW}━━━ Updating install.sh ━━━${NC}"
    DOWNLOAD_URL="https://github.com/v-merli/php-harbor/releases/download/${TAG_NAME}/${PACKAGE_NAME}.tar.gz"
    
    if grep -q "RELEASE_URL=" install.sh; then
        sed -i.bak "s|RELEASE_URL=.*|RELEASE_URL=\"$DOWNLOAD_URL\"|" install.sh
        rm install.sh.bak
        echo -e "${GREEN}✓${NC} install.sh updated with new release URL"
        echo ""
        echo "Remember to commit and push the updated install.sh:"
        echo "  git add install.sh"
        echo "  git commit -m 'Update install.sh URL for $VERSION'"
        echo "  git push"
        echo ""
    else
        echo -e "${YELLOW}⚠${NC} Could not find RELEASE_URL in install.sh"
        echo "Update it manually to: $DOWNLOAD_URL"
        echo ""
    fi
else
    # Local mode - show manual instructions
    echo -e "${YELLOW}━━━ Next Steps (Manual) ━━━${NC}"
    echo ""
    echo "1. Test the tarball locally:"
    echo "   tar -xzf $OUTPUT_DIR/${PACKAGE_NAME}.tar.gz -C /tmp/test"
    echo ""
    echo "2. Publish to GitHub:"
    echo "   ./create-release.sh $VERSION"
    echo ""
    echo "   Or manually:"
    echo "   - Go to: https://github.com/v-merli/php-harbor/releases/new"
    echo "   - Tag: $TAG_NAME"
    echo "   - Title: PHPHarbor $VERSION"
    echo "   - Upload: $OUTPUT_DIR/${PACKAGE_NAME}.tar.gz"
    echo ""
fi

echo -e "${GREEN}━━━ Done! ━━━${NC}"
echo ""
